### ISSUE TITLE
About the instances data for testing

### ISSUE THREAD

**Issue by Alicia0422** [boldm1/two-stage-robust-RCPSP#1]
Thank you for sharing the code and results for the paper. I‘m very sorry to ask whether the instances data for testing can also be provided. Thank you！

**Comment by boldm1** [comment]
The instances used are the j30 RCPSP instances from the PSPLIB, which can be downloaded from http://www.om-db.wi.tum.de/psplib/getdata_sm.html. We generated our robust instances from these deterministic instances by setting the maximum deviation of the duration of each activity to be half its deterministic duration, rounded up to the nearest integer (and the maximum duration is therefore nominal duration + maximum deviation). And then for each of the 480 instances the j30 data set, 3 robust problems have been generated by setting Gamma to be 3, 5, and 7. So we used a total total of 1440 robust instances. I hope this helps!

**Comment by Alicia0422** [comment]
> The instances used are the j30 RCPSP instances from the PSPLIB, which can be downloaded from http://www.om-db.wi.tum.de/psplib/getdata_sm.html. We generated our robust instances from these deterministic instances by setting the maximum deviation of the duration of each activity to be half its deterministic duration, rounded up to the nearest integer (and the maximum duration is therefore nominal duration + maximum deviation). And then for each of the 480 instances the j30 data set, 3 robust problems have been generated by setting Gamma to be 3, 5, and 7. So we used a total total of 1440 robust instances. I hope this helps!

Oh I got it! Thank you very much!
